# Generated by Django 4.1.5 on 2023-01-24 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CobrosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_init', models.DateField(max_length=250)),
                ('date_end', models.DateField(max_length=250)),
                ('cost_effective', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cost_credit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='courselist', to='CobrosApp.course')),
            ],
        ),
    ]
