# Generated by Django 4.1.5 on 2023-01-25 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CobrosApp', '0002_cohorte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.DateField(max_length=250)),
                ('identification', models.DateField(max_length=250)),
                ('cell_phone', models.DecimalField(decimal_places=2, max_digits=19)),
                ('address', models.DecimalField(decimal_places=2, max_digits=19)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='userlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
