# Generated by Django 4.1.5 on 2023-02-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CobrosApp', '0005_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('count', models.IntegerField(max_length=3)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
